---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devworkspace-controller
  labels:
    app.kubernetes.io/name: devworkspace-controller
    app.kubernetes.io/part-of: devworkspace-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: devworkspace-controller
      app.kubernetes.io/part-of: devworkspace-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: devworkspace-controller
        app.kubernetes.io/part-of: devworkspace-operator
      annotations:
        kubectl.kubernetes.io/restartedAt: ""
    spec:
      serviceAccountName: devworkspace-controller
      containers:
        - name: devworkspace-controller
          image: quay.io/devfile/devworkspace-controller:next
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "devworkspace-operator"
            - name: SERVICE_ACCOUNT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            - name: RELATED_IMAGE_plugin_redhat_developer_web_terminal_4_5_0
              value: "quay.io/eclipse/che-machine-exec:nightly"
            - name: RELATED_IMAGE_plugin_redhat_developer_web_terminal_nightly
              value: "quay.io/eclipse/che-machine-exec:nightly"
            - name: RELATED_IMAGE_plugin_redhat_developer_web_terminal_dev_4_5_0
              value: "quay.io/eclipse/che-machine-exec:nightly"
            - name: RELATED_IMAGE_plugin_redhat_developer_web_terminal_dev_nightly
              value: "quay.io/eclipse/che-machine-exec:nightly"
            - name: RELATED_IMAGE_plugin_eclipse_cloud_shell_nightly
              value: "quay.io/eclipse/che-machine-exec:nightly"
            - name: RELATED_IMAGE_web_terminal_tooling
              value: "registry.redhat.io/codeready-workspaces/plugin-openshift-rhel8:2.1"
            - name: RELATED_IMAGE_openshift_oauth_proxy
              value: "openshift/oauth-proxy:latest"
          ports:
            - name: webhook-server
              containerPort: 8443
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: devworkspace-controller
    app.kubernetes.io/part-of: devworkspace-operator
  name: workspace-controller
spec:
  ports:
    - targetPort: webhook-server
      protocol: TCP
      port: 443
  selector:
    app.kubernetes.io/name: devworkspace-controller
    app.kubernetes.io/part-of: devworkspace-operator
