apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/name: devworkspace-controller
    app.kubernetes.io/part-of: devworkspace-operator
  name: devworkspace-controller-serving-cert
  namespace: openshift-operators
spec:
  dnsNames:
  - devworkspace-webhookserver.openshift-operators.svc
  - devworkspace-webhookserver.openshift-operators.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: devworkspace-controller-selfsigned-issuer
  secretName: devworkspace-operator-webhook-cert
