apiVersion: workspace.che.eclipse.org/v1alpha1
kind: Workspace
metadata:
  name: java-mysql
spec:
  started: true
  devfile:
    apiVersion: 1.0.0
    commands:
      - actions:
          - command: mvn clean install
            component: tools
            type: exec
            workdir: ${CHE_PROJECTS_ROOT}/web-java-spring-petclinic
        name: maven build
    components:
      - alias: theia-ide
        id: eclipse/che-theia/7.1.0
        type: cheEditor
      - id: eclipse/che-machine-exec-plugin/7.1.0
        type: chePlugin
      - id: redhat/java/latest
        memoryLimit: 1280MiB
        type: chePlugin
      - type: dockerimage
        alias: tools
        endpoints:
          - name: 8080/tcp
            port: 8080
        env:
          - name: JAVA_OPTS
            value: -XX:MaxRAMPercentage=50.0 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10
              -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
              -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom
              -Duser.home=/home/user
          - name: MAVEN_OPTS
            value: $(JAVA_OPTS)
        image: quay.io/eclipse/che-java8-maven:nightly
        memoryLimit: 700Mi
        mountSources: true
        volumes:
          - containerPath: /home/user/.m2
            name: m2
      - alias: mysql
        endpoints:
          - attributes:
              discoverable: "true"
              public: "false"
            name: db
            port: 3306
        env:
          - name: MYSQL_USER
            value: petclinic
          - name: MYSQL_PASSWORD
            value: password
          - name: MYSQL_DATABASE
            value: petclinic
          - name: PS1
            value: $(echo ${0})\\$
        image: centos/mysql-57-centos7
        memoryLimit: 300Mi
        mountSources: true
        type: dockerimage
    projects:
      - name: web-java-spring-petclinic
        source:
          location: https://github.com/spring-projects/spring-petclinic.git
          type: git
