---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: devworkspace-controller
  labels:
    app.kubernetes.io/name: devworkspace-controller
    app.kubernetes.io/part-of: devworkspace-operator
subjects:
- kind: ServiceAccount
  name: devworkspace-controller
  # Namespace must be replaced with controller's namespace
  namespace: ${NAMESPACE}
roleRef:
  kind: ClusterRole
  name: devworkspace-controller
  apiGroup: rbac.authorization.k8s.io
