# This workspace could be created only with the latest che-plugin-registry
# To archive it you should modify /deploy/registry/local/deployment.yaml:
# 1. Put quay.io/eclipse/che-plugin-registry:nightly
# 2. Remove CHE_SIDECAR_CONTAINERS_REGISTRY_TAG env var
# A bit later it will be a default registry
apiVersion: workspace.che.eclipse.org/v1alpha1
kind: Workspace
metadata:
  name: cloud-shell
spec:
  started: true
  devfile:
    apiVersion: 0.0.1
    metadata:
      name: cloud-shell
    components:
      - alias: cloud-shell
        type: cheEditor
        id: eclipse/cloud-shell/nightly
      - type: dockerimage
        memoryLimit: 256Mi
        alias: dev
        image: 'eclipse/che-remote-plugin-openshift-connector-0.0.17:7.2.0'
        env:
          - value: '\[\e[34m\]>\[\e[m\]\[\e[33m\]>\[\e[m\]'
            name: PS1
