apiVersion: v2
publisher: che-incubator
name: command-line-terminal-dev
version: nightly
type: Che Editor
displayName: Dev Command Line Terminal
title: Dev Command Line Terminal
description: Command Line Terminal provides the ability to start a terminal inside
  the OpenShift Console. The development version does not run with TLS enabled and
  is intended for development purposes only.
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
repository: https://github.com/eclipse/che-machine-exec/
firstPublicationDate: "2020-06-01"
category: Other
spec:
  endpoints:
    - name: command-line-terminal
      public: true
      targetPort: 4444
      attributes:
        protocol: http
        type: ide
        discoverable: false
        secure: true
        cookiesAuthEnabled: true
  containers:
    - name: command-line-terminal
      image: "quay.io/eclipse/che-machine-exec:nightly"
      command: ["/go/bin/che-machine-exec",
                "--authenticated-user-id", "$(CHE_WORKSPACE_CREATOR)",
                "--idle-timeout", "$(CHE_WORKSPACE_IDLE_TIMEOUT)"]
      ports:
        - exposedPort: 4444
      env:
        - name: USE_BEARER_TOKEN
          value: true
