kind: DevWorkspace
apiVersion: workspace.devfile.io/v1alpha2
metadata:
  name: theia
spec:
  started: true
  template:
    projects:
      - name: web-nodejs-sample
        git:
          remotes:
            origin: "https://github.com/che-samples/web-nodejs-sample.git"
    components:
      - name: theia
        plugin:
          kubernetes:
            name: theia-next
            namespace: devworkspace-plugins
      - name: terminal
        plugin:
          kubernetes:
            name: machine-exec
            namespace: devworkspace-plugins
    commands:
      - id: say-hello
        exec:
          component: theia
          commandLine: echo "Hello from $(pwd)"
          workingDir: ${PROJECTS_ROOT}/project/app
