apiVersion: v1
kind: Service
metadata:
  name: manager-service
  namespace: system
spec:
  ports:
  - name: https
    port: 443
    targetPort: conversion
    protocol: TCP
  - name: metrics
    port: 8443
    targetPort: metrics
  selector:
    app.kubernetes.io/name: devworkspace-controller
    app.kubernetes.io/part-of: devworkspace-operator
