#
# Copyright (c) 2020-2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
name: Next Dockerimage

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout devworkspace-operator source code
      uses: actions/checkout@v2
    - name: Docker Build & Push
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
        registry: quay.io
        repository: devfile/devworkspace-controller
        dockerfile: ./build/Dockerfile
        tags: next
        tag_with_sha: true
    - name: Docker Build & Push (Project Clone)
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
        registry: quay.io
        repository: devfile/project-clone
        dockerfile: ./project-clone/Dockerfile
        tags: next
        tag_with_sha: true
